/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nekkan_jnitest_Vector3F */

#ifndef _Included_dev_nekkan_jnitest_Vector3F
#define _Included_dev_nekkan_jnitest_Vector3F
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_nekkan_jnitest_Vector3F
 * Method:    plus
 * Signature: (Ldev/nekkan/jnitest/Vector3F;)Ldev/nekkan/jnitest/Vector3F;
 */
JNIEXPORT jobject JNICALL Java_dev_nekkan_jnitest_Vector3F_plus
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
