/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nekkan_jnitest_MainKt */

#ifndef _Included_dev_nekkan_jnitest_MainKt
#define _Included_dev_nekkan_jnitest_MainKt
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
