/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nekkan_jnitest_HelloWorld */

#ifndef _Included_dev_nekkan_jnitest_HelloWorld
#define _Included_dev_nekkan_jnitest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_nekkan_jnitest_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_nekkan_jnitest_HelloWorld_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
