[package]
name = "rust"
version = "0.1.0"
authors = ["nekkan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
jni = "0.18.0"